### PR TITLE
Work out modularization

### PR DESCRIPTION
**Pull request by gbrlsnchs**
@simrat39 You probably already merged some new stuff, but I wanted to open this PR anyway, since I've been working on this for the last few days. Please feel free to extract whatever feels useful to you.

### CODE REVIEW

**Comment by simrat39** [comment]
Thanks for the PR! This is some cool stuff, I will definitely pickup most of it

**Comment by simrat39** [comment]
A few notes:

image
Hover actions have moved to the hover dialog, so i'm not sure if we need a telescope selector for it

**Comment by simrat39** [comment]
image

Having a telescope extension is a great idea, although I would still like the default RustRunnables command to open a telescope selector by default if the user has it installed, with a pre configured theme, if anyone wants something custom they can use the extension

**Comment by simrat39** [comment]
ok ive done a few changes in the modularization branch
https://github.com/simrat39/rust-tools.nvim/tree/modularization
we'll merge this when the telescope extensions are also done

**Comment by gbrlsnchs** [comment]
@simrat39 Thanks for considering these changes. Would you mind finishing up this PR? I can't do it for the next few weeks and am not actively using these tools at the moment, so it would take time if it were to depend on me right now.

I also think you might do a better job than me because you can fine tune things based on your plans for the tool.

**Comment by simrat39** [comment]
@gbrlsnchs Hi, most of the stuff in this PR has already been merged, I just have to do the telescope extensions and I'll get that done asap but I need to learn a bit more about how telescope works

**Comment by simrat39** [comment]
Closing because we have almost everything from this PR merged

**Comment by gbrlsnchs** [comment]
Sorry about this becoming stale, forcing you to port it over manually. Since I was not using this actively, I wouldn't be able to attest quality regarding my changes.

Anyway, I'm glad I could help with at least some ideas! I'll be back to Rust pretty soon and am hoping to get back to using this awesome plugin as well!

**Pull request closed without merging**
