### PR TITLE
use vim.ui  module

### PR DESCRIPTION
**Pull request by IndianBoy42**
replace vim.fn.input with vim.ui.input

replace vim.fn.inputlist with vim.ui.select

This allows users to customize and implement new selection modes

### CODE REVIEW

**Comment by simrat39** [comment]
With this we can also remove the telescope code, could you do that please? If not then lmk and i'll do it

**Comment by IndianBoy42** [comment]
Thats a good idea, I'll check it out and try

**Comment by IndianBoy42** [comment]
In fact, I think its a good idea to leave a link to how to replace `vim.ui.select` with a telescope based handler (which is what I do)

Maybe this plugin: https://github.com/nvim-telescope/telescope-ui-select.nvim

Where should I put this? or maybe you change the README.md to how you want it

**Comment by simrat39** [comment]
Put it on the top of the readme as a breaking change, and one other place (wherever you deem fit). 

Do we really need a select configuration? I feel like vim.ui.* should be enough, lmk what you think

**Comment by IndianBoy42** [comment]
> Do we really need a select configuration? I feel like vim.ui.* should be enough, lmk what you think

I'm not sure, but I added it for two reasons:

1. more customization for not much cost is probably a good idea.
2. Some selection menus want fuzzy search like [telescope-ui-select.nvim](https://github.com/nvim-telescope/telescope-ui-select.nvim), while some selection menus have small enough amount of choices (like code_actions) that something like [popui.nvim](https://github.com/hood/popui.nvim) makes more sense where you just `j,k` to select an entry. 

This point is also quite up to personal preferences

**Comment by IndianBoy42** [comment]
It would be interesting (for another day) to see if the `RustCodeAction` menu could be changed to just nesting `vim.ui.select`

**Comment by simrat39** [comment]
@IndianBoy42  the select logic is wrong, it will never be called, and you're calling it in the wrong place as well (should be called inside the handler not outside). Let's just remove it for now and see if we need it later on.

**Comment by simrat39** [comment]
Also the popup.nvim dependency can be removed now, and plenary can be moved to a line above dap

**Comment by IndianBoy42** [comment]
> Also the popup.nvim dependency can be removed now, and plenary can be moved to a line above dap

Did you mean just removing the line from README.md? I can't find any code that uses the popup plugin

**Comment by simrat39** [comment]
whoops accidentally merged this, this is broken as of now

**Pull request merged**
