### PR TITLE
Fix hover actions windows lost focus

### PR DESCRIPTION
**Pull request by lfdominguez**
When the hover action windows appear lost the focus or never get it.

### CODE REVIEW

**Comment by simrat39** [comment]
You can press the same key combo for your hover to activate actions, automatically focusing is not ideal because most of the times the user wants to see the hover info, not activate an action

**Comment by lfdominguez** [comment]
Sorry, I don't share your opinion about "most of the times". If i execute the hover actions info is because i want to do something, not to see if there are something to do for only view that and not take any action.

**Comment by lfdominguez** [comment]
This behavior I understand if the popup show on real hover, for example, when the cursor is on an entry that has some hover actions, then show that actions and if you want get the focus and execute one of them... but in this case, the user is who requesting the hover actions to do something.

**Comment by simrat39** [comment]
That's fair, then we should do a config option which is false by default to toggle this behavior

**Comment by lfdominguez** [comment]
I agree... :clap:

**Comment by lfdominguez** [comment]
@simrat39 now is configurable...

**Comment by simrat39** [comment]
Thanks for the PR!

**Pull request merged**
