### PR TITLE
fix: `apply_text_edits` requires offset_encoding option

### PR DESCRIPTION
**Pull request by kunish**
Closes https://github.com/simrat39/rust-tools.nvim/issues/127

See:
https://github.com/neovim/neovim/issues/14090#issuecomment-1012005684

### CODE REVIEW

**Comment by unrealhoang** [comment]
imo, passing through `offset_encoding` from the caller to the `old_func` is better than hardcoding an `offset_encoding`.

**Comment by Mathijs-Bakker** [comment]
> imo, passing through `offset_encoding` from the caller to the `old_func` is better than hardcoding an `offset_encoding`.
https://github.com/hrsh7th/nvim-cmp/issues/726#issuecomment-1012213386

**Comment by simrat39** [comment]
> imo, passing through `offset_encoding` from the caller to the `old_func` is better than hardcoding an `offset_encoding`.

Yes we should definitely do this. I can maybe do it on the weekend, have been really busy lately

**Comment by hrryndrsn** [comment]
Thank you! Completion via nvim-vmp working well now :)

**Pull request closed without merging**
