### PR TITLE
Add RustToggleInlayHints command

### PR DESCRIPTION
**Pull request by krady21**
Hi.
I learned about this plugin from your reddit post a few days ago and found it really useful. As I never like having inlay hints open all the time, I made a new command to toggle them. This is my first time writing lua, so feel free to correct me if I made any mistakes.

### CODE REVIEW

**Comment by simrat39** [comment]
Thanks for the PR's, this looks good but I have to merge the modularization branch first, then we can look at this

**Comment by simrat39** [comment]
https://github.com/simrat39/rust-tools.nvim/commit/7f5295d3ec13d4d2769092a9e3dc849d56e6a7e7 Thanks for the pr :+1:

**Comment by simrat39** [comment]
btw make sure that opts.tools.autoSetHints is set to false else the hints will reappear on write, or when u escape insert mode and what not

**Comment by krady21** [comment]
thanks for the heads up

**Comment by simrat39** [comment]
> Thanks for the heads up. I've also realized that I forgot to add the command in the readme disappointed

no worries I added it now https://github.com/simrat39/rust-tools.nvim/commit/230b147432556f2c751e7348a4915e30fd3f8023

**Pull request closed without merging**
